### ISSUE TITLE
2.4 Pull Requests: Destination [typos]

### ISSUE THREAD

**Issue by joannaotmianowska** [briisk/briisk-git#9]
2.4 ...
`Why? You should create big PRs. The more code reviewer ahs to check, the more mistakes he/she can skip. Also there should'nt be unfinished functionality in the main branch.`

Isn't it supposed to be `shouldn't` instead of `should` as PRs can't be big? 
Typo `ahs` > `has`
Typo `should'nt` > `shouldn't`

**Comment by dakolech** [comment]
Right, thanks
